### ISSUE TITLE
Disabled icon changes while context menu visible.

### ISSUE THREAD

**Issue by CinemaVision** [CinemaVision/script.cinemavision#55] opened 2017-02-10 21:34 UTC
In the Sequence Editor, when opening a context menu while the cursor has a disabled module as focus the icon for disabled changes to the icon for enabled until you exit the context menu.

**Comment by ruuk** [comment] 2017-02-18 21:16
Duplicate of issue #6

**Closed by ruuk** 2017-02-18 21:16 UTC
Labels: Duplicate
